### ISSUE TITLE
Make the post-processing locally instead of on the PROD repository

### ISSUE THREAD

**Issue by ColinMaudry** [ColinMaudry/datagouvfr-rdf#22]
This enables to prevent small time of data inconsistency on the PROD repo and to load the final data in a single atomic transaction.
Currently:

1) Convert to RDF
2) Upload to live repo
3) Apply SPARQL postprocessing on live repo

The problem is that during the SPARQL postprocessing, the live data is incomplete (5-10 minutes).

Instead:

1) Convert to RDF
2) Apply SPARQL postprocessing on temp repo (local or remote)
3) Get RDF from temp repo
4) Upload to live repo

Fuseki in the best candidate for the local post-processing due to its low footprint and its in-memory storage.

**Comment by ColinMaudry** [comment]
All good except that now I upload all data (70 MB, 754k triples) at once (one PUT) instead of four, and @dydra responds that the request is too large:

```
curl -v -X PUT -H "Content-type: text/turtle" --data-binary @"all.ttl" http://???@dydra.com/colin-maudry/datagouvfr
* Hostname was NOT found in DNS cache
* Adding handle: conn: 0x1f03d70
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x1f03d70) send_pipe: 1, recv_pipe: 0
*   Trying 148.251.144.130...
* Connected to dydra.com (148.251.144.130) port 80 (#0)
* Server auth using Basic with user '???'
> PUT /colin-maudry/datagouvfr HTTP/1.1
> Authorization: Basic ????????????
> User-Agent: curl/7.34.0
> Host: dydra.com
> Accept: */*
> Content-type: text/turtle
> Content-Length: 70744716
> Expect: 100-continue
>
< HTTP/1.1 413 Request Entity Too Large
* Server nginx/1.4.6 (Ubuntu) is not blacklisted
< Server: nginx/1.4.6 (Ubuntu)
< Date: Sat, 14 Mar 2015 22:29:13 GMT
< Content-Type: text/html
< Content-Length: 207
< Connection: close
<
<html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.4.6 (Ubuntu)</center>
</body>
</html>
* Closing connection 0
```

**Comment by ColinMaudry** [comment]
@jaw111 suggests I use [SPARQL Update LOAD](http://www.w3.org/TR/sparql11-update/#load) instead of HTTP PUT, as the data is then streamed.

**Comment by lisp** [comment]
both are "streamed".
with a load request (which is also a PUT, but of the query to the sparql endpoint rather than the date to the repository resource) the store retrieves the data to be imported, which avoids the request size limit.
the statement count limit remains.

**Comment by jaw111** [comment]
Sounds like Colin might have outgrown the beta :)

Date: Mon, 16 Mar 2015 10:09:03 -0700

**Comment by ColinMaudry** [comment]
I'll use Apache Fuseki2 on the app server until Dydra supports graph MOVE on dydra.com.
