### ISSUE TITLE
Add a dgfr:machineReadable property (true|false) based on the content type

### ISSUE THREAD

**Issue by ColinMaudry** [ColinMaudry/datagouvfr-rdf#37]
The following content types are considered machine readable:

* application/xml
* application/rdf+xml
* application/json
* text/csv
* application/csv (I know it's not right, but data.gouv.fr has 800+ of these)
* text/tsv
* text/plain
* text/turtle
* text/trig
* text/n-triples

**Comment by ColinMaudry** [comment]
In the frame of ColinMaudry/beheader#6, I will mint the MIME type `application/shp+zip` and add it to the list of machine readable formats.

**Comment by ColinMaudry** [comment]
I could apply this property in [beheader](https://github.com/ColinMaudry/beheader), but some content types may come from other sources than beheader detection... such as the original metadata from the open data portal.

**Comment by ColinMaudry** [comment]
Moved to ColinMaudry/beheader#7

**Comment by ColinMaudry** [comment]
Oops

**Comment by jdesboeufs** [comment]
http://inspire.ec.europa.eu/media-types/
Next major release of inspire.data.gouv.fr will land in September ;)
